### ISSUE TITLE
this project need a Readme

### ISSUE THREAD

**Issue by Doriangue** [JustDams/faceitFinder#23]
i think readme can be usefull
![bitmoji](https://sdk.bitmoji.com/render/panel/65194a5a-410b-4f1a-8687-e1c23f2d8400-b2a27f17-742d-4893-8037-a73033ae7db0-v1.png?transparent=1&palette=1&width=246)

**Comment by Sheraw91** [comment]
i m working on it 👯‍♂️

**Comment by JustDams** [comment]
> i think readme can be usefull
> ![bitmoji](https://camo.githubusercontent.com/13740794fefc57c158b25e81c1072179a848559584c919291d6bb28c6c096572/68747470733a2f2f73646b2e6269746d6f6a692e636f6d2f72656e6465722f70616e656c2f36353139346135612d343130622d346631612d383638372d6531633233663264383430302d62326132376631372d373432642d343839332d383033372d6137333033336165376462302d76312e706e673f7472616e73706172656e743d312670616c657474653d312677696474683d323436)

I will see.
